# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WashMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=10, verbose_name='洗衣机编号')),
                ('dormitory_building_number', models.IntegerField(verbose_name='寝室楼号')),
                ('state', models.CharField(choices=[('F', 'Free'), ('W', 'Work'), ('B', ' Breakdown'), ('D', 'Dirty')], max_length=1, verbose_name='运行状态')),
            ],
            options={
                'db_table': 'washmachine',
                'permissions': (('view_washmachine', 'Can view the washmachine'), ('remove_washmachine', 'Can remove a washmachine'), ('modify_washmachine', 'Can modify a washmachine'), ('findOne_washmachine', 'Can find a washmachine'), ('findAllOfCondition_washmachine', 'Can find all washmachines of condition')),
            },
        ),
    ]
