# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegralTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_account', models.CharField(max_length=30, verbose_name='交易用户')),
                ('transaction_time', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('trading_integral', models.IntegerField(verbose_name='交易积分')),
                ('balance', models.IntegerField(verbose_name='积分余额')),
                ('transaction_type', models.CharField(choices=[('R', 'Recharge'), ('P', 'Pay'), ('B', 'Back')], max_length=1, verbose_name='交易类型')),
                ('remarks', models.CharField(max_length=300, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_account', models.CharField(max_length=30, verbose_name='交易用户')),
                ('transaction_time', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('trading_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='交易金额')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='交易余额')),
                ('transaction_type', models.CharField(choices=[('R', 'Recharge'), ('P', 'Pay'), ('B', 'Back')], max_length=1, verbose_name='交易类型')),
                ('remarks', models.CharField(max_length=300, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.IntegerField(verbose_name='洗衣机编号')),
                ('account', models.CharField(max_length=30, verbose_name='账号')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='起始时间')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=30, verbose_name='学号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'emale')], max_length=1, verbose_name='性别')),
                ('mobile_phone', models.CharField(max_length=15, verbose_name='手机号码')),
                ('dormitory_building_number', models.IntegerField(verbose_name='寝室楼号')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='余额')),
                ('credit', models.IntegerField(default=100, verbose_name='信用分')),
                ('integral', models.IntegerField(default=0, verbose_name='积分')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30, verbose_name='账号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('salt', models.CharField(max_length=50, verbose_name='加盐')),
                ('avatar', models.CharField(max_length=60, verbose_name='头像')),
                ('category', models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('R', 'Repair')], max_length=1, verbose_name='用户类型')),
            ],
        ),
        migrations.CreateModel(
            name='WashMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.IntegerField(verbose_name='洗衣机编号')),
                ('dormitory_building_number', models.IntegerField(verbose_name='寝室楼号')),
                ('state', models.CharField(choices=[('F', 'Free'), ('W', 'Work'), ('B', ' Breakdown'), ('D', 'Dirty')], max_length=1, verbose_name='运行状态')),
            ],
        ),
    ]
