# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='integraltransaction',
            table='integraltransaction',
        ),
        migrations.AlterModelTable(
            name='moneytransaction',
            table='moneytransaction',
        ),
        migrations.AlterModelTable(
            name='queue',
            table='queue',
        ),
        migrations.AlterModelTable(
            name='stuinfo',
            table='stuInfo',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='washmachine',
            table='washmachine',
        ),
    ]
