# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20171206_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='dormitory_building_number',
            field=models.IntegerField(null=True, verbose_name='寝室楼号'),
        ),
    ]
