# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20171206_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
